name: dot_money_expense
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
 sdk: ">=3.1.5 <4.0.0"

dependencies:
 cupertino_icons: ^1.0.2
 google_fonts: 6.1.0
 hive: ^2.2.3
 get_cli: ^1.8.1
 get: 4.6.6
 flutter:
  sdk: flutter
 flutter_screenutil: ^5.9.3
 intl: ^0.19.0
 hive_flutter: ^1.1.0
 hive_generator: ^2.0.1
 flutter_conditional_rendering: ^2.1.0

dev_dependencies:
 build_runner: ^2.4.9
 flutter_lints: ^2.0.0
 flutter_test:
  sdk: flutter

flutter:
 uses-material-design: true
 assets:
  - assets/
